name: auth_logic
description: >-
  Production-ready Flutter auth package with MVVM + Cubit. Login, register, 
  OTP, token refresh, retry, and colored network logs.
version: 1.0.0
homepage: https://github.com/EslaamAshraaf/Auth.Logic
repository: https://github.com/EslaamAshraaf/Auth.Logic
issue_tracker: https://github.com/EslaamAshraaf/Auth.Logic/issues

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  dio: ^5.11.0
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  phone_numbers_parser: ^9.0.26
  device_info_plus: ^13.2.0
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^8.2.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
